### ISSUE TITLE
Can't receive data

### ISSUE THREAD

**Issue by joaoantoniocardoso** [BasicAirData/BluetoothHelper#3]
Hi,

I'm using an Arduino Uno board with a HC-05 bluetooth module. It was configured and tested with another apps like "Blueooth Terminal" and "Bluetooth Monitor".

I'm trying to use the example you gave and it is really nice, it connects, disconnects and sends data, but when I try to receive: nothing happens.

I have toogled a breakpoint at the overrode `onBluetoothHelperConnectionStateChanged` of my `setBluetoothHelperListener` but it is never triggered. 

I have uncommented all the log lines from the class but gave-me only this:
**edit 1:** I have now tried to breakpoint inside the `MessageReceived` method and we got the message but have some error to pass it ahead:
> [#] Devicename doesn't match: ASUS_Z00LD
[#] Devicename doesn't match: ZS_CPU
[#] Devicename match found: cpu
[#] Socket connected. Opening streams....
[#] Input Stream opened
[#] Output Stream opened
[#] Listener fired: onBluetoothHelperConnectionStateChanged = true
[#] Message received: abc
[#]  Listener fired: onBluetoothHelperMessageReceived
[!] Failed to receive message: Only the original thread that created a view hierarchy can touch its views.
[#] Message received: abc
...

**Edit 2:** Ok, nevermind, I now understand that is nothing wrong with the library, the issue solved using a `runOnUiThread`.

Thanks

**Comment by GrazianoCapelli** [comment]
Correct. The listener is fired by a worker thread.
You have to execute your code into the UI thread in order to update UI views.
I committed two `Log.w` lines (commented out) into `ConnectedThreadClass_Read.run` method for general future debug purpose.

Maybe we could insert the `runInUiThread` code (commented out) directly into the example.

**Comment by JLJu** [comment]
"Maybe we could insert the runInUiThread code (commented out) directly into the example"
That is good thinking.
