### ISSUE TITLE
Publish the library on JCenter and Maven Central

### ISSUE THREAD

**Issue by GrazianoCapelli** [BasicAirData/BluetoothHelper#5]
To do when the library will be deeply tested.

**Comment by GrazianoCapelli** [comment]
We have to choose the definitive artifact name.

I propose the following tags:

`<groupId>eu.basicairdata</groupId>` <- No reference to the author in the groupId
`<artifactId>bluetoothhelper</artifactId>`
`<version>1.0.5</version>`

**Comment by JLJu** [comment]
No reference in the group id seems fine, I've to say more than Open. Author references shall be present within the code.

**Comment by GrazianoCapelli** [comment]
Today the library has been published on JFrog Bintray.

I'm waiting the JCenter and Maven Central linking (the process usually takes a week).
I'll test the artifact from both JCenter and Maven Central before update the repo files, publish the new instructions on the root README and close the issue.

Stay tuned! 😃

**Comment by GrazianoCapelli** [comment]
Library published on JCenter.
Starting from now it's possible to use the BluetoothHelper library simply adding the following line into the dependencies section of build.gradle (Module: app):

`compile 'eu.basicairdata:bluetoothhelper:1.0.5'`

**Comment by GrazianoCapelli** [comment]
Library published on Maven Central too.
The code for inclusion is:
```xml
<dependency>
    <groupId>eu.basicairdata</groupId>
    <artifactId>bluetoothhelper</artifactId>
    <version>1.0.5</version>
    <type>pom</type>
</dependency>
```
