### ISSUE TITLE
Comment the code for Doxygen

### ISSUE THREAD

**Issue by GrazianoCapelli** [BasicAirData/BluetoothHelper#6]
Doxygen is the de facto standard tool for generating documentation from annotated Java sources.

We should add the comments to the library in order to automate the creation of the library documentation.
We could publish the documentation on BasicAirData website in HTML format, and here in PDF.

**Comment by JLJu** [comment]
Copy that

**Comment by GrazianoCapelli** [comment]
I added the comments into BluetoothHelper class for Doxygen automatic documentation.
